version: '3'

volumes:
  etcd:

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd
    hostname: etcd 
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCD_DATA_DIR: /etcd-data
      ETCD_NAME: etcd
      ETCDCTL_API: 3 
      ALLOW_NONE_AUTHENTICATION: yes
      # ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      # ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      # ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
      # ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name
      - etcd
      - --initial-advertise-peer-urls
      - http://etcd:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://etcd:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
    volumes:
      - etcd:/etcd-data

  e3w:
    image: soyking/e3w:latest
    container_name: e3w
    restart: always
    volumes:
      - ./config/e3w/config.ini:/app/conf/config.default.ini
    ports:
      - 8880:8080
    depends_on:
      - etcd
