version: "3"

volumes:
  etcd:

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    hostname: etcd
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - etcd:/bitnami/etcd/data
    network_mode: host

  e3w:
    image: evildecay/etcdkeeper:latest
    container_name: e3w
    restart: always
    environment:
      - ETCDCTL_API=3
    ports:
      - 8880:8080
    command: ["-h", "0.0.0.0", "-p", "8080", "--etcdhosts", "http://etcd:2379"]
    depends_on:
      - etcd
    network_mode: host
