version: "3"

volumes:
  postgres:
  mysql:
  redis:
  mongodb:
  influxdb:
  chronograf:

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    network_mode: host

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - mysql:/var/lib/mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=@123456
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=@123456
      - TZ=Asia/Shanghai

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    network_mode: host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=@123456

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
      - ./config/influxdb/config.yml:/etc/influxdb2/config.yml
      - ./config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    network_mode: host
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=@123456
      - DOCKER_INFLUXDB_INIT_ORG=Jack
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket

  chronograf:
      image: chronograf:latest
      ports:
        - 8888:8888
      volumes:
        - chronograf:/var/lib/chronograf
      depends_on:
        - influxdb
      environment:
        - INFLUXDB_URL=http://localhost:8086
        - INFLUXDB_USERNAME=admin
        - INFLUXDB_PASSWORD=@123456