version: "3"

networks:
  app:
    external: true

volumes:
  etcd:

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    hostname: etcd
    restart: always
    ports:
      - 2379:2379
    environment:
      - ETCD_DATA_DIR=/bitnami/etcd/data
      - ETCD_NAME=etcd-node1
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd:/bitnami/etcd/data
    networks:
      - app

  e3w:
    image: soyking/e3w:0.1.0
    container_name: e3w
    ports:
      - 8880:8880
    volumes:
      - ./config/e3w/config.ini:/app/conf/config.default.ini
    depends_on:
      - etcd
    networks:
      - app
