version: '3'

volumes:
  grafana:
  loki:
  prometheus:

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-explorer-app
      - GF_INSTALL_PLUGINS=redis-app
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: always
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    ports:
      - 9100:9100

  docker-exporter:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    ports:
      - 8080:8080

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    restart: always
    ports:
      - 9187:9187
    depends_on:
      - postgres
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:@123456@left4dead2.me:5432/postgres?sslmode=disable

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    restart: always
    ports:
      - 9104:9104
    depends_on:
      - mysql
    environment:
      - DATA_SOURCE_NAME=root:@123456@(mysql:3306)/mysql

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: always
    ports:
      - 9121:9121
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://left4dead2.me:6379

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/loki.yaml
    restart: always
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml
      - loki:/loki
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    depends_on:
      - loki
    volumes:
      - ./config/promtail/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail.yaml
    network_mode: host