version: "3"

networks:
  app:

volumes:
  postgres:
  mysql:
  redis:

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=NO_ENGINE_SUBSTITUTION
    environment:
      - MYSQL_ROOT_PASSWORD=@123456
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=@123456
      - TZ=Asia/Shanghai
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app
