server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - left4dead2.me
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: apisix
    pipeline_stages:
      - match:
          selector: '{filename=~".+apisix\\/access\\.log"}'
          stages:
            - regex:
                # apisix config: access_log_format: "$remote_addr - $remote_user [$time_local] $http_host \"$request\" $status $body_bytes_sent $request_time \"$http_referer\" \"$http_user_agent\" $upstream_addr $upstream_status $upstream_response_time \"$upstream_scheme://$upstream_host$upstream_uri\""
                # e.g.: 172.19.0.1 - - [14/Jan/2022:07:42:17 +0000] left4dead2.me:9080 "PUT /apisix/admin/routes/1 HTTP/1.1" 403 150 0.000 "-" "curl/7.81.0" - - - "http://left4dead2.me:9080"
                expression: '(?P<remote_addr>\S+) - (?P<remote_user>.+) \[(?P<ts>.+)\] (?P<host>[\.\w]+(:\d+)?) "(?P<method>\w+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+)'
            - timestamp:
                source: ts
                format: 02/Jan/2006:15:04:05 -0700
            - labels:
                http_status: status
      - match:
          selector: '{filename=~".+apisix\\/error\\.log"}'
          stages:
            - regex:
                # e.g.: 2022/01/13 10:55:11 [warn] 51#51: *7 [lua] plugin.lua:222: load_stream(): new plugins: {"ip-restrictio...
                expression: '(?P<ts>[\d\/: ]+) \[(?P<level>\w+)\]'
            # Make level upper case
            - replace:
                expression: '(\w+)'
                source: level
                replace: "{{ .Value | ToUpper }}"
            - timestamp:
                source: ts
                format: 2006/01/02 15:04:05
            - labels:
                level:
    static_configs:
      - targets:
          - left4dead2.me
        labels:
          job: apisix
          __path__: /var/aslog/apisix/*log
      - targets:
          - left4dead2.me
        labels:
          job: apisix-dashboard
          __path__: /var/aslog/apisix-dashboard/*log