global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
