apisix:
  node_listen: 9080
  enable_ipv6: false

  allow_admin:
    - 127.0.0.1
    - 172.25.0.0/16 # app

  admin_key:
    - name: admin
      key: admin
      role: admin
    - name: viewer
      key: viewer
      role: viewer

  enable_control: true
  control:
    ip: 0.0.0.0
    port: 9090

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 10
  user: root
  password: etcd-@123456
