apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.16.0.3:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:

  - name: Postgres
    type: postgres
    url: 172.16.0.3:5432
    user: postgres
    jsonData:
      database: postgres
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
    secureJsonData:
      password: '@123456'

  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    basicAuth: false
    editable: true
    enabled: true
    jsonData:
      connection: mongodb://172.16.0.3:27017
      user: root
    secureJsonData:
      password: '@123456'

#   - name: MySQL
#     type: mysql
#     url: 172.16.0.3:3306
#     user: root
#     jsonData:
#       database: mysql
#       maxOpenConns: 100
#       maxIdleConns: 100
#       maxIdleConnsAuto: true
#       connMaxLifetime: 14400
#     secureJsonData:
#       password: '@123456'

  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://172.16.0.3:8086
    jsonData:
      version: Flux
      organization: jack
      defaultBucket: jack
      tlsSkipVerify: true
    secureJsonData:
      token: '@12345678'

  - name: Redis
    type: redis
    access: proxy
    isDefault: true
    version: 1
    url: redis://172.16.0.3:6379
    jsonData:
      tlsAuth: false
      tlsSkipVerify: true

#   - name: Elastic
#     type: elasticsearch
#     access: proxy
#     url: http://172.16.0.3:9200
#     jsonData:
#       index: '[metrics-]YYYY.MM.DD'
#       interval: Daily
#       timeField: '@timestamp'
#
#   - name: elasticsearch-v7-filebeat
#     type: elasticsearch
#     access: proxy
#     url: http://172.16.0.3:9200
#     jsonData:
#       index: '[filebeat-]YYYY.MM.DD'
#       interval: Daily
#       timeField: '@timestamp'
#       logMessageField: message
#       logLevelField: fields.level
#       dataLinks:
#         - datasourceUid: my_jaeger_uid # Target UID needs to be known
#           field: traceID
#           url: '$${__value.raw}' # Carefu