apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:

  - name: Postgres
    type: postgres
    url: localhost:5432
    user: postgres
    secureJsonData:
      password: '@123456'
    jsonData:
      database: grafana
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false

  - name: Redis
    type: redis
    access: proxy
    isDefault: true
    version: 1
    url: redis://localhost:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true

  - name: MongoDB
    type: mongodb
    access: proxy
    basicAuth: false
    editable: true
    enabled: true
    jsonData:
      user: root
    secureJsonData:
      password: '@123456'

  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: organization
      defaultBucket: bucket
      tlsSkipVerify: true
    secureJsonData:
      token: '@123456'

#   - name: Elastic
#     type: elasticsearch
#     access: proxy
#     url: http://localhost:9200
#     jsonData:
#       index: '[metrics-]YYYY.MM.DD'
#       interval: Daily
#       timeField: '@timestamp'
#
#   - name: elasticsearch-v7-filebeat
#     type: elasticsearch
#     access: proxy
#     url: http://localhost:9200
#     jsonData:
#       index: '[filebeat-]YYYY.MM.DD'
#       interval: Daily
#       timeField: '@timestamp'
#       logMessageField: message
#       logLevelField: fields.level
#       dataLinks:
#         - datasourceUid: my_jaeger_uid # Target UID needs to be known
#           field: traceID
#           url: '$${__value.raw}' # Carefu